apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 2

  selector:
    matchLabels:
      type: app

  template:
    metadata:
      name: mypod
      labels:
        type: app
    spec:
      containers:
      - name: mycontainer
        image: heenashinganjude/myweb
        ports:
        - containerPort: 80
          name: http 
